version: '3.8'

services:
  web:
    image: ilhamnadhif/weplant-backend:1.0
    container_name: weplant-backend
    networks:
      - weplant
    ports:
      - 8080:8080
    environment:
      - GO_ENV=developer
      - MONGO_URI=mongodb://ilham:ilham@mongodb:27017
      - CLOUDINARY_URL=cloudinary://287213174684114:M9D51dyLW4H3gAac8ApaurTD_UI@weplant
      - CLOUDINARY_FOLDER=weplant
      - MIDTRANS_SERVER_KEY=SB-Mid-server-uwDke7AME__PwAx48cbcBjlu
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: weplant-mongo
    ports:
      - 27017:27017
    networks:
      - weplant
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ilham
      - MONGO_INITDB_ROOT_PASSWORD=ilham
    volumes:
      - weplant-mongo-volume:/data/db

networks:
  weplant:
    name: weplant

volumes:
  weplant-mongo-volume:
    name: weplant-mongo-volume